### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by musaBoya** [kadirlua/Socket#11]
I can't compile in ubuntu 24.04 
![image](https://github.com/kadirlua/Socket/assets/145341844/3e0aa990-b4db-41f3-86a6-602fc8c4e595)

**Comment by musaBoya** [comment]
![image](https://github.com/kadirlua/Socket/assets/145341844/41d06164-9c27-44b2-9f7b-7ea4c5f5c5c5)

After I changed BUILD_SHARED_LIBS to OFF the problem is gone .

**Comment by kadirlua** [comment]
Thanks for reporting the issue. There is no problem compiling on Windows with default options. When I tried on Ubuntu (WSL2), the same problem occours. I have checked the log and saw there is a problem with cmake because It does not recognize we try to build the library as shared but It tries to compile BaseException as static. Therefore, there is mismatch between the libraries. We can fix this issue by passing -DBUILD_SHARED_LIBS=ON flag while configuring cmake. But I will change something on BaseException library, maybe defaulting to shared library.
